### ISSUE TITLE
Add Waves/burst data

### ISSUE THREAD

**Issue by CorentinLouis** [das-developers/das2py#12]
Add functions that read and plot Juno/Waves/burst data from PDS (assigned to CorentinLouis)

**Comment by cpiker** [comment]
Hi Corentin

That's a  rather specific function for a general purpose program.  Typically the way Jeremy handles this is to create a script that has mission-specific details.  Is there any reason that a loadable script wouldn't suffice in this case?

**Comment by CorentinLouis** [comment]
Hi Chris, I'm so sorry, I opened this issue by mistake (wrong github window ...). You can close (delete) it, sorry again.

**Comment by cpiker** [comment]
Absolutely no worries.  Hope all is well.

**Comment by cpiker** [comment]
Easiest issue I've closed all day :-)
