### ISSUE TITLE
Typo in ACE FM2 Digital HSK Name

### ISSUE THREAD

**Issue by KaiwenS7** [das-developers/das2py#13]
"Numebr of Bad Commands" is the property name for data name="bad_cmd"

**Comment by cpiker** [comment]
Hum.  I think this issue might be for a different project.  das2py has no specific knowledge of ACE.  Can you provide more detail?

**Comment by KaiwenS7** [comment]
My bad. It's mainly an issue with the L1 packet stream information. One of the data properties has a typo in it. Which project needs to be updated for that? I have another bug to report on that as well, since it relates to data coming from the L0 packets in Das2.

**Comment by cpiker** [comment]
Since this is a public project, I'll close the issue, and send info in another forum.
