### ISSUE TITLE
Installation through wheel error

### ISSUE THREAD

**Issue by roglans** [das-developers/das2py#17]
On Ubuntu 20.04.6. Attempting to build a wheel to install in my python3.11 environment.
```
~/Documents/das2py$ env DAS2C_LIBDIR=$PWD/../das2C/build. DAS2C_INCDIR=$PWD/../das2C python3.11 -m build

src/_das2.c:753:10: fatal error: py_dft.h: No such file or directory
  753 | #include "py_dft.h"
      |          ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```

It looks like the source header referenced in _das2.c can't be found despite being in the src/ directory. I solved this issue by changing the path to be absolute... but that is obviously not a general solution.

**Comment by cpiker** [comment]
Hey, thanks for the clear error message.   I'm able to replicate the problem, seems to only affect the Linux version, Visual Studio builds don't have the same issue.  Working on a correction now...

**Comment by cpiker** [comment]
The header files weren't in MANIFEST.in, so out-of-tree builds such as performed when generating python wheels were not finding them.   Commit 502720c adds the necessary headers.
