### ISSUE TITLE
PIP Package

### ISSUE THREAD

**Issue by cpiker** [das-developers/das2py#2]
Currently the only pre-packaged version of das2py with it's das2C dependency included is an Anaconda3 package.  Producing a PIP package, presumably in wheel format, is a high priority.

**Comment by BaptisteCecconi** [comment]
Hi Chris, I've talked with my colleague Sonny (@Septaris). He would love this feature, so that he can include das2py in the Solar Orbiter ground segment pipelines.

**Comment by cpiker** [comment]
Having an active user for the packages certainty bumps the priority.  Nice to know they would be in active use, since it reduces the likely hood of having broken packages laying about.
Let me see what I can do over the next week or so.  In the meantime, any one who want's to send in a pull request for pip packaging is certainly welcome to join in.

**Comment by Septaris** [comment]
I started a dedicated branch with docker containers to test wheel builds: https://github.com/Septaris/das2py/tree/2-pip-package

**Comment by Septaris** [comment]
I have a working automated demo for Windows using docker and travis:
1. In the das2c repo:
  a.  a dedicated das2c image is generated by travis (https://github.com/Septaris/das2C/blob/docker-hub-deployment/.travis.yml) and pushed to docker hub (https://hub.docker.com/repository/docker/babouh/das2c/tags?page=1)
2. In the das2py repo, on push: 
  a. travis (https://github.com/Septaris/das2py/blob/2-pip-package/.travis.yml) pull the das2c image, build a das2py docker image and generate the wheel file
  b. travis copy the wheel file from the docker container and deploy it in repository releases
3. We can test the wheel releases `pip install https://github.com/Septaris/das2py/releases/download/untagged-66d7f9c6f68ba134710e/das2py-2.3.2-cp37-cp37m-win_amd64.whl` and then setup the automated Pypi deployment

Is it okay for you ? If so, we have to do the same for linux and mac.

**Comment by cpiker** [comment]
Of course that's okay, It's open source, you're welcome to use it however you wish :).

Since I've never generated a PIP package myself, nor used docker, nor travis, I'm completely unqualified at this point to comment on this method for generating packages.  If these are useful to you and you have time to support them then... great!

My only concern is I'd like to bring associated efforts like this "in-band" or at least provide links in the main ReadME.md here so that all das2py packages can be found from one place.  Do you mind if I add you as a contributor to this repo so that you can at least update the master ReadMe.md with appropriate description and links?  You're also welcome to start a separate branch here if some alterations were needed to build the source as PIP packages.

Thanks again for taking up this task, I look forward to testing your packages.

**Comment by cpiker** [comment]
Latest commit to main builds as a binary wheel on Linux.  Other platforms to follow shortly.  Closing the issue.

**Comment by cpiker** [comment]
...forgot to hit the close button
