### ISSUE TITLE
Numpy.Object error in PyCDF

### ISSUE THREAD

**Issue by KaiwenS7** [das-developers/das2py#9]
In [das2/pycdf/__init__.py line 3799](https://github.com/das-developers/das2py/blob/90552754f86fbd63ff4175520547f06eea8f4dcf/das2/pycdf/__init__.py#L3799) the use of d.dtype==numpy.object is used. This numpy.object is depreciated in all values of numpy past version 1.20 ([source](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)), and you will be unable to generate CDFs using newer versions of numpy.

**Comment by cpiker** [comment]
Ah, thanks.  So to fix this and insure it stays fixed I'd propose two changes:
1. Fix the source bug (of course) 
2. Have the `make test` target also run through all the examples instead of just the scripts under `./test`.
